config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'

  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @movie = Movie.find(params[:bookmark][:movie_id])
    @bookmark.list = @list
    @bookmark.movie = @movie
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'new'
    end
  end

  def destroy
    @list = List.find(params[:id])
    @bookmark = Bookmark.find_by(list_id: params[:id])
    @bookmark.destroy

    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render 'new'
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit "Add movie", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/index.html.erb
</div>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1542204165-65bf26472b9b?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1567&q=80);">
  <div class="container">
    <h1>WatchList</h1>
    <p>Create a list of movies to share with your friends!</p>
  </div>
</div>

<div class="container">
  <div class="cards-container my-4">
    <% @lists.each do |list| %>
      <%= link_to list_path(list) do %>
        <div class="flip-container">
            <div class="flipper" >
              <div class="front">
                <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))">

                </div>
              </div>
              <div class="back">
                <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))">
                  <%= list.name %>
                </div>
              </div>
            </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<!-- <div class="container">
  <div class="cards-container my-4">
    <% @lists.each do |list| %>
      <%= link_to list_path(list) do %>

        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path "#{list.name}.png" %>)">
          <%= list.name %>
        </div>

      <% end %>
    <% end %>
  </div>
</div>
 -->

app/views/lists/new.html.erb
<h1>Create a new list</h1>

<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.submit "Create List", class: "btn btn-primary" %>
<% end %>

app/views/lists/show.html.erb
</div>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4))">
  <div class="container">
    <h1 class="mt-1"><%= @list.name %></h1>
  </div>
</div>

<div class="container">

  <div class="page-container my-4">
    <div class="movies-container">
      <% @list.movies.each do |movie| %>
        <div class="movie-card d-flex flex-column">
          <img src="<%= movie.poster_url %>" alt="movie-poster" class="card-image">
          <div class="card-description d-flex flex-column flex-grow-1 justify-content-start">
            <p class="title"><%= movie.title %> <i class="fas fa-circle mx-1"></i> <span class="rating"><%= movie.rating %><i class="fas fa-star ml-1"></i></span></p>
            <p class="overview flex-grow-1"><%= movie.overview %></p>
            <div class="card-foot d-flex justify-content-between align-items-center">
              <p class="comment"><i class="fas fa-quote-left mr-2"></i><%= movie.bookmarks[0].comment %></p>
              <%= link_to bookmark_path, method: :delete, data: {confirm: 'Are you sure?' }, class: "delete" do %>
                <i class="fas fa-trash"></i>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="right-column">
      <div class="add-movie p-3">
        <h3>Add a movie</h3>
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.input :comment %>
          <%= f.association :movie %>
          <%= f.submit "Add movie", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/shared/_navbar.html.erb
    <div class="navbar-lewagon d-flex py-4">
      <%= link_to lists_path, class: "button mx-3 text-reset" do %>
        My Lists
      <% end %>
      <%= link_to new_list_path, class: "button mx-3 text-reset" do %>
        Create List
      <% end %>
    </div>